# -*- coding: utf-8 -*-
"""AOCday2_2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i2Qs_mOn8ToCba8mECwWtqVUZL5satz_
"""

def is_game_possible(game, red_count, green_count, blue_count):
    for subset in game:
      #split on the commas
        cubes = subset.split(', ')
        for cube in cubes:
            count, color = cube.split(' ')
            count = int(count)
            if color == 'red' and count > red_count:
                return False
            elif color == 'green' and count > green_count:
                return False
            elif color == 'blue' and count > blue_count:
                return False
    return True

def possible_games_sum(games, red_count, green_count, blue_count):
    possible_sum = 0
    for game in games:
        game_id, subsets = game.split(': ')
        game_id = int(game_id.split(' ')[-1])
        if is_game_possible(subsets.split('; '), red_count, green_count, blue_count):
            possible_sum += game_id
    return possible_sum

# Read data from file
with open("AOCday2.txt", "r") as file:
    gamesData = file.read().splitlines()

# Given cube counts
red_count = 12
green_count = 13
blue_count = 14

# Calculate the sum of IDs for possible games
result = possible_games_sum(gamesData, red_count, green_count, blue_count)

print(result)